name: Create docker image + Intergration Tests

on:
  push:
    tags:
      - "**"
    branches:
      - "main"
  pull_request:

jobs:
    intergration-tests:
        runs-on: ubuntu-latest
        steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - uses: actions/checkout@v4
        - uses: actions/setup-go@v4
          with:
            go-version: "1.20.5"

        - name: Build simd binary
          run: make build
    
        - name: Build docker
          run: make build-docker
        
        - name: Start docker
          run: make start-docker
        
        - name: Run Intergration Test
          run: make test-integration-docker

